# Generated by Django 5.1.5 on 2025-01-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, upload_to='slider', verbose_name='Баннер')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
