# Generated by Django 5.1.5 on 2025-01-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ключевые слова для категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ключевые слова для категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='email_en',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='email_ru',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='images',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='title_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ключевые слова для товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ключевые слова для товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
