# Generated by Django 5.1.5 on 2025-01-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
